[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_app_solana_anchor = "G3uLtDyW1UJAZGsWJpC3XfkG3vdednmCYu5KV6RqYRyk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sujoynath/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
