[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_app_solana_anchor = "EqaKtMpHuhqRbakvfMGoLXHZsV6dCD3DRp6uqEU5pbVq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sujoynath/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
